"""Generate docs/EVALUATION_SET.md and docs/BLIND_QUESTION_PACK.md from the source of truth.

    python make_docs.py

EVALUATION_SET.md lists every question, why it is in the set, and which check grades it. It is
generated from data/eval_questions.json, data/eval_key_facts.json and the other data/*_questions.json
files, so it cannot drift from
what runs.

BLIND_QUESTION_PACK.md is a hand-off for someone (a classmate, or a different model in a fresh
session) to write questions from the raw documents alone, so part of the evaluation is not
written by the person who wrote the documents and the system.
"""
import harness as H


def facts_text(groups):
    return "; ".join(" / ".join(f"`{a}`" for a in g) for g in groups) if groups else "(abstain)"


def graded_by(q):
    if q["kind"] == "out_of_scope":
        return "abstention (code)"
    if q["kind"] == "partially_answerable":
        return "key facts on the answerable part (code), says the rest is missing (code), faithfulness (judge)"
    return "key facts (code), citation (code), faithfulness (judge)"


def eval_set_doc(qs):
    L = ["# The evaluation set", "",
         "Generated by `make_docs.py` from `data/eval_questions.json`, `data/eval_key_facts.json` and the other `data/*_questions.json` files.",
         "",
         "Every main-set label was written before the system ran: `expected_divisions`, `source_doc_ids` and "
         "`expected_answer_summary` in `data/eval_questions.json` come from the three fixed cross-division hooks in "
         "`data/generation_prompts.md`. The key facts in `data/eval_key_facts.json` were added afterwards, derived from those "
         "summaries and verified against the source documents by `self_test.py`; one (CD4) was corrected "
         "when that self-test showed it demanded an id the question already gives.", "",
         "Question types follow the A1 break-it categories: two documents needed (the cross-division "
         "questions), vocabulary mismatch, distractor, and absent but plausible (which tests abstention), "
         "plus two that probe invention harder: false premise, and partially answerable.", "",
         "Honest limit: the main, false-premise, break-it and partially answerable sets were all written by the author of the "
         "documents (or by the assistant that built them). Only the `independent` set, if present, was not. "
         "Results are reported per set.", ""]
    order = [("main", "cross_division", "Main: two documents needed, across divisions (11)"),
             ("main", "single_division", "Main: single division (9)"),
             ("main", "out_of_scope", "Main: absent but plausible, one per division (3) -- tests abstention"),
             ("extra", "near_miss", "False premise: the question assumes something the documents contradict (2)"),
             ("breaker", None, "Break-it: vocabulary mismatch, distractor, absent but plausible (6)"),
             ("partial", None, "Partially answerable: one part in the documents, one part in none (6)"),
             ("independent", None, "Independent: written by someone who has not seen the project")]
    for set_name, kind, title in order:
        rows = [q for q in qs if q["set"] == set_name and (kind is None or q["kind"] == kind)]
        if not rows:
            continue
        L += [f"## {title}", "", "| id | hook | divisions needed | source docs | key facts (all groups required; any alternative in a group) | why it is here | graded by |",
              "|---|---|---|---|---|---|---|"]
        for q in rows:
            L.append(f"| {q['id']} | {q.get('hook', '')} | {', '.join(q['expected_divisions']) or '-'} | "
                     f"{', '.join(q['source_doc_ids']) or '-'} | {facts_text(q['facts'])} | {q['why']} | {graded_by(q)} |")
        L.append("")
    L += ["## What each check can and cannot tell you", "",
          "- **Key facts (code):** the answer contains the specific facts. Catches wrong or vague answers. "
          "Cannot catch a right fact wrapped in a wrong claim.",
          "- **Citation (code):** the answer cites at least one document and only documents that were retrieved.",
          "- **Faithfulness (judge model):** every claim is supported by the retrieved notes. Cannot tell "
          "whether the answer is correct. The judge is hand-checked with `--agreement`.",
          "- **Abstention (code):** on out-of-scope questions the answer is exactly the abstention phrase.", ""]
    return "\n".join(L)


def blind_pack():
    L = ["# Blind question pack", "",
         "**For whoever writes the questions (a classmate, or a different model in a fresh session).**", "",
         "Below are 18 internal documents from a fictional conglomerate. Do not use any outside knowledge. "
         "Write questions ONLY from these documents.", "",
         "Write exactly 6 questions:", "",
         "1. Three that need facts from documents in at least two different divisions (`fnb-`, `cnc-`, `jwl-`).",
         "2. Two that need only one division.",
         "3. One that the documents do NOT answer but sounds like they might.", "",
         "For each, give the answer you found and 1-3 short exact phrases from the documents that any correct "
         "answer must contain (numbers, ids and dates are best). Reply as JSON in exactly this shape:", "",
         "```json",
         '{"questions": [',
         '  {"id": "IND1", "kind": "cross_division", "question": "...", "expected_divisions": ["fnb", "cnc"],',
         '   "source_doc_ids": ["fnb-01", "cnc-01"], "groups": [["exact phrase", "alternative wording"], ["another fact"]],',
         '   "why": "one line on what this tests"},',
         '  {"id": "IND6", "kind": "out_of_scope", "question": "...", "expected_divisions": [], "source_doc_ids": [], "groups": [], "why": "..."}',
         "]}",
         "```", "",
         "Each inner list in `groups` is one required fact; list alternative wordings inside it. "
         "Save the JSON as `data/independent_questions.json`, then run `python self_test.py` "
         "(it checks every fact appears in the cited documents) and `python run_eval.py --run`.", "",
         "---", ""]
    for doc_id, rel in H.DOC_ID_TO_PATH.items():
        L += [f"## DOCUMENT {doc_id}", "", (H.DATA_DIR / rel).read_text(encoding="utf-8").strip(), "", "---", ""]
    return "\n".join(L)


if __name__ == "__main__":
    qs = H.load_questions()
    (H.ROOT / "docs" / "EVALUATION_SET.md").write_text(eval_set_doc(qs), encoding="utf-8")
    (H.ROOT / "docs" / "BLIND_QUESTION_PACK.md").write_text(blind_pack(), encoding="utf-8")
    print(f"wrote docs/EVALUATION_SET.md ({len(qs)} questions) and docs/BLIND_QUESTION_PACK.md")
